# Generated by Django 4.0 on 2022-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=255)),
                ('nonce', models.CharField(blank=True, default=0, max_length=255)),
                ('data', models.TextField(blank=True, max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
