# Generated by Django 4.0 on 2022-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_remove_block_id_block_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
