# Generated by Django 4.0 on 2022-03-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('blocks', '0004_block_orphan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(to='transactions.Transaction'),
        ),
    ]
