# Generated by Django 4.0 on 2022-03-17 22:39

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_rename_orphan_block_added_to_bc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='transactions',
        ),
        migrations.AddField(
            model_name='block',
            name='transaction',
            field=models.TextField(default=1, verbose_name=transactions.models.Transaction),
            preserve_default=False,
        ),
    ]
