# Generated by Django 4.0 on 2022-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_remove_block_transactions_block_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='transaction',
            field=models.TextField(),
        ),
    ]
