# Generated by Django 4.0 on 2022-03-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_alter_block_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='transaction',
            new_name='tx_hash',
        ),
    ]
