# Generated by Django 4.0 on 2022-03-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=7, default=0.0, max_digits=12)),
                ('balance_in_ngn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('public_key', models.TextField(blank=True, unique=True)),
                ('private_key', models.TextField(blank=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('receive_key', models.CharField(blank=True, max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.user')),
            ],
        ),
    ]


