# Generated by Django 4.0 on 2022-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_rename_transaction_block_tx_hash'),
        ('blockschain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='chain',
            field=models.ManyToManyField(to='blocks.Block'),
        ),
    ]
